import NavBar from "@/components/NavBar.jsx";
import Task from "@/models/Task.js";
import { connectDB } from "@/utils/mongoose.js";
import { Inter } from 'next/font/google';
import { Toaster } from "react-hot-toast";
import './globals.css';


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const loadTasks = async () => {
  connectDB();
  const tasks = await Task.find();
  return tasks;
}

export default async function RootLayout({ children }) {
  const tasks = await loadTasks();

  return (
    <html lang="en">
      <body className={inter.className}>
        <NavBar tasks={tasks} />
        <main className="container mx-auto px-5 mt-4">
          {children}
          <Toaster />
        </main>
      </body>
    </html>
  )
}
